/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { EventEmitter, JSX } from "@stencil/core";
import { SlideAttributes, SlideTemplate, StorageFile, Template, TenorCategory, TenorGif, UnsplashPhoto, Waves } from "@deckdeckgo/editor";
import { SelectedTarget } from "./app/types/editor/selected-target";
import { MonacoEditorOptions } from "@deckdeckgo/monaco-editor";
import { PrismLanguage } from "./app/types/editor/prism-language";
import { InitStyleColor } from "./app/utils/editor/color.utils";
import { DeckAction } from "./app/types/editor/deck-action";
import { EditAction } from "./app/types/editor/edit-action";
import { ImageHelper } from "./app/helpers/editor/image.helper";
import { Expanded } from "./app/types/core/settings";
import { ImageAction } from "./app/types/editor/image-action";
import { SlotType } from "@deckdeckgo/studio";
import { ListStyle } from "./app/types/editor/list-style";
import { TargetElement } from "./app/types/editor/target-element";
import { MoreAction } from "./app/types/editor/more-action";
import { ItemReorderEventDetail } from "@ionic/core";
import { InitTemplate } from "./app/utils/editor/create-slides.utils";
export namespace Components {
    interface AppActionAddSlide {
        "popoverCssClass": string;
        "slidesLength": number | undefined;
    }
    interface AppActionBusy {
        "iconName": string;
    }
    interface AppActionHelp {
        "link": boolean;
    }
    interface AppActionShare {
    }
    interface AppActionsDeck {
        "animatePrevNextSlide": EventEmitter;
        "deckDidChange": EventEmitter;
        "fullscreen": boolean;
        "slides": JSX.IntrinsicElements[];
        "toggleFullScreen": EventEmitter;
    }
    interface AppActionsDeckEditor {
        "fullscreen": boolean;
        "selectDeck": () => Promise<void>;
        "selectStep": (element: HTMLElement | undefined) => Promise<void>;
        "slideNumber": number;
        "slides": JSX.IntrinsicElements[];
        "touch": (element: HTMLElement, autoOpen?: boolean) => Promise<void>;
    }
    interface AppActionsElement {
        "blurSelectedTarget": () => Promise<void>;
        "elementFocus": EventEmitter;
        "reset": () => Promise<void>;
        "slideCopy": EventEmitter;
        "slideTransform": EventEmitter;
        "touch": (element: HTMLElement | undefined, autoOpen?: boolean) => Promise<void>;
        "unSelect": () => Promise<void>;
    }
    interface AppAssetData {
        "data": StorageFile;
    }
    interface AppAssetImage {
        "image": UnsplashPhoto | TenorGif | StorageFile | Waves | TenorCategory;
    }
    interface AppBlock {
        "selectedTarget": SelectedTarget;
    }
    interface AppBorderRadius {
        "selectedTarget": SelectedTarget;
    }
    interface AppBottomSheet {
    }
    interface AppBoxShadow {
        "selectedTarget": SelectedTarget;
    }
    interface AppBreadcrumbs {
        "slideNumber": number;
    }
    interface AppCloseMenu {
    }
    interface AppCode {
        "codeDidChange": EventEmitter<HTMLElement> | undefined;
        "selectedTarget": HTMLElement;
    }
    interface AppCodeEditor {
        "code": string;
        "options": MonacoEditorOptions;
    }
    interface AppCodeLanguages {
        "codeDidChange": EventEmitter<HTMLElement> | undefined;
        "currentLanguage": PrismLanguage | undefined;
        "selectedTarget": HTMLElement;
    }
    interface AppColor {
        "defaultColor": string;
        "initColor": () => Promise<InitStyleColor>;
        "loadColor": () => Promise<void>;
    }
    interface AppColorChart {
        "selectedTarget": HTMLElement;
    }
    interface AppColorCode {
        "selectedTarget": HTMLElement;
    }
    interface AppColorQrcode {
        "selectedTarget": HTMLElement;
    }
    interface AppColorSides {
        "selectedTarget": HTMLElement;
        "template": 'split' | 'author';
    }
    interface AppColorTextBackground {
        "colorType": 'text' | 'background';
        "deck": boolean;
        "selectedTarget": HTMLElement;
        "slide": boolean;
    }
    interface AppColorWordCloud {
        "selectedTarget": HTMLElement;
    }
    interface AppControl {
    }
    interface AppCopyStyle {
        "selectedTarget": HTMLElement;
    }
    interface AppCreateSlide {
    }
    interface AppDeckEditor {
        "autoConnect": boolean;
        "initNewDeck": () => Promise<void>;
    }
    interface AppDeckFonts {
        "deckElement": HTMLElement;
    }
    interface AppDeckHeaderFooter {
        "deckDidChange": EventEmitter<HTMLElement>;
        "deckElement": HTMLElement;
    }
    interface AppDeckStyle {
        "deckDidChange": EventEmitter<HTMLElement>;
    }
    interface AppDeckTransition {
        "deckElement": HTMLDeckgoDeckElement;
    }
    interface AppDemo {
        "selectedTarget": HTMLElement;
    }
    interface AppEditMode {
    }
    interface AppEditSlide {
        "selectedTarget": SelectedTarget;
        "slideDidChange": EventEmitter<HTMLElement>;
    }
    interface AppEditSlideAuthor {
        "selectedTarget": HTMLElement;
        "slideDidChange": EventEmitter<HTMLElement>;
    }
    interface AppEditSlideChart {
        "selectedTarget": HTMLElement;
        "slideDidChange": EventEmitter<HTMLElement>;
    }
    interface AppEditSlideQrcode {
        "selectedTarget": HTMLElement;
        "slideDidChange": EventEmitter<HTMLElement>;
    }
    interface AppEditSlideUser {
        "selectedTarget": SelectedTarget;
        "slideDidChange": EventEmitter<HTMLElement>;
    }
    interface AppEditor {
        "autoConnect": boolean;
    }
    interface AppElementStyle {
        "imageHelper"?: ImageHelper;
        "imgDidChange"?: EventEmitter<HTMLElement>;
        "selectedTarget": SelectedTarget;
    }
    interface AppEmbed {
    }
    interface AppExpansionPanel {
        "expanded": Expanded;
        "expander": boolean;
    }
    interface AppFullscreenInfo {
    }
    interface AppGetHelp {
    }
    interface AppGif {
    }
    interface AppImageChoice {
        "deck": boolean;
        "deleteBackground": boolean;
        "selectedTarget": HTMLElement;
        "slide": boolean;
    }
    interface AppImageElement {
        "selectedTarget": HTMLElement;
        "slide": boolean;
    }
    interface AppImageHistory {
        "deck": boolean;
        "slide": boolean;
    }
    interface AppImageStyle {
        "selectedTarget": HTMLElement;
    }
    interface AppLinks {
    }
    interface AppList {
        "selectedTarget": HTMLElement;
    }
    interface AppLogo {
    }
    interface AppMath {
        "mathDidChange": EventEmitter<HTMLElement>;
        "selectedTarget": HTMLElement;
    }
    interface AppMenu {
    }
    interface AppMoreElementActions {
        "clone": boolean;
        "images": boolean;
        "notes": boolean;
        "transform": boolean;
    }
    interface AppMoreShareOptions {
    }
    interface AppNavigation {
        "actions": 'all' | 'none' | 'editor-less';
    }
    interface AppNavigationEnd {
        "editorActions": boolean;
    }
    interface AppNavigationStart {
    }
    interface AppNoTemplates {
    }
    interface AppNotes {
        "selectedTarget": HTMLElement;
    }
    interface AppPlayground {
        "selectedTarget": HTMLElement;
    }
    interface AppPlaygroundPlaceholder {
    }
    interface AppPollOptions {
        "selectedTarget": HTMLElement;
        "slideDidChange": EventEmitter<HTMLElement>;
    }
    interface AppPopoverConfirm {
    }
    interface AppPresent {
        "fullscreen": boolean;
    }
    interface AppPublish {
    }
    interface AppPublishDone {
        "publishedUrl": string;
    }
    interface AppPublishEdit {
    }
    interface AppPublishTags {
        "disableRemove": boolean;
        "tags": string[];
    }
    interface AppRandomGif {
        "keyword": string;
    }
    interface AppRemoteConnect {
    }
    interface AppRemoteRequest {
    }
    interface AppReveal {
        "selectedTarget": HTMLElement;
    }
    interface AppRoot {
    }
    interface AppRootControl {
    }
    interface AppRootView {
    }
    interface AppSelectTargetElement {
        "chart": boolean;
        "code": boolean;
        "headerFooter": boolean;
        "image": boolean;
        "qrCode": boolean;
        "sides": boolean;
        "slide": boolean;
        "textTarget": boolean;
        "transition": boolean;
        "wordCloud": boolean;
    }
    interface AppShape {
        "selectedTarget": HTMLElement;
    }
    interface AppShare {
    }
    interface AppShareOptions {
    }
    interface AppSlideNavigate {
    }
    interface AppSlidePreview {
        "deckRef": HTMLDeckgoDeckElement;
    }
    interface AppSlideThumbnail {
        "deck": HTMLDeckgoDeckElement;
        "slide": HTMLElement;
    }
    interface AppSlideWarning {
    }
    interface AppSlideWarningInfo {
        "lowContrast": boolean;
        "overflow": boolean;
    }
    interface AppSlidesAside {
        "activeIndex": number;
        "deckRef": HTMLDeckgoDeckElement;
    }
    interface AppSlotType {
        "selectedTarget": HTMLElement | undefined;
        "skip": boolean;
        "slotTypes": SlotType[] | undefined;
    }
    interface AppSpinner {
    }
    interface AppStorageAdmin {
        "storageFile": StorageFile;
    }
    interface AppStorageData {
    }
    interface AppStorageFiles {
        "admin": boolean;
        "folder": 'data' | 'images';
        "resetAndSearch": () => Promise<void>;
    }
    interface AppStorageImages {
    }
    interface AppSyncInfo {
    }
    interface AppTemplateShowcase {
        "author": boolean;
        "editable": boolean;
        "template": Template;
    }
    interface AppTemplatesCharts {
    }
    interface AppTemplatesCommunity {
    }
    interface AppTemplatesContent {
        "highlight": boolean;
        "highlightIndex": number | undefined;
        "selected": boolean;
    }
    interface AppTemplatesDefault {
    }
    interface AppTemplatesSplit {
        "highlight": boolean;
        "highlightIndex": number | undefined;
        "selected": boolean;
        "vertical": boolean;
    }
    interface AppTemplatesTitle {
        "highlight": boolean;
        "highlightIndex": number | undefined;
        "selected": boolean;
    }
    interface AppText {
        "selectedTarget": SelectedTarget;
    }
    interface AppTransformElement {
        "selectedTarget": HTMLElement;
    }
    interface AppTransformSlide {
        "selectedTarget": HTMLElement;
    }
    interface AppUnpublish {
    }
    interface AppUnsplash {
    }
    interface AppUserInfo {
        "displayAvatar": boolean;
    }
    interface AppWaves {
    }
    interface AppYoutube {
        "selectedTarget": HTMLElement;
    }
}
declare global {
    interface HTMLAppActionAddSlideElement extends Components.AppActionAddSlide, HTMLStencilElement {
    }
    var HTMLAppActionAddSlideElement: {
        prototype: HTMLAppActionAddSlideElement;
        new (): HTMLAppActionAddSlideElement;
    };
    interface HTMLAppActionBusyElement extends Components.AppActionBusy, HTMLStencilElement {
    }
    var HTMLAppActionBusyElement: {
        prototype: HTMLAppActionBusyElement;
        new (): HTMLAppActionBusyElement;
    };
    interface HTMLAppActionHelpElement extends Components.AppActionHelp, HTMLStencilElement {
    }
    var HTMLAppActionHelpElement: {
        prototype: HTMLAppActionHelpElement;
        new (): HTMLAppActionHelpElement;
    };
    interface HTMLAppActionShareElement extends Components.AppActionShare, HTMLStencilElement {
    }
    var HTMLAppActionShareElement: {
        prototype: HTMLAppActionShareElement;
        new (): HTMLAppActionShareElement;
    };
    interface HTMLAppActionsDeckElement extends Components.AppActionsDeck, HTMLStencilElement {
    }
    var HTMLAppActionsDeckElement: {
        prototype: HTMLAppActionsDeckElement;
        new (): HTMLAppActionsDeckElement;
    };
    interface HTMLAppActionsDeckEditorElement extends Components.AppActionsDeckEditor, HTMLStencilElement {
    }
    var HTMLAppActionsDeckEditorElement: {
        prototype: HTMLAppActionsDeckEditorElement;
        new (): HTMLAppActionsDeckEditorElement;
    };
    interface HTMLAppActionsElementElement extends Components.AppActionsElement, HTMLStencilElement {
    }
    var HTMLAppActionsElementElement: {
        prototype: HTMLAppActionsElementElement;
        new (): HTMLAppActionsElementElement;
    };
    interface HTMLAppAssetDataElement extends Components.AppAssetData, HTMLStencilElement {
    }
    var HTMLAppAssetDataElement: {
        prototype: HTMLAppAssetDataElement;
        new (): HTMLAppAssetDataElement;
    };
    interface HTMLAppAssetImageElement extends Components.AppAssetImage, HTMLStencilElement {
    }
    var HTMLAppAssetImageElement: {
        prototype: HTMLAppAssetImageElement;
        new (): HTMLAppAssetImageElement;
    };
    interface HTMLAppBlockElement extends Components.AppBlock, HTMLStencilElement {
    }
    var HTMLAppBlockElement: {
        prototype: HTMLAppBlockElement;
        new (): HTMLAppBlockElement;
    };
    interface HTMLAppBorderRadiusElement extends Components.AppBorderRadius, HTMLStencilElement {
    }
    var HTMLAppBorderRadiusElement: {
        prototype: HTMLAppBorderRadiusElement;
        new (): HTMLAppBorderRadiusElement;
    };
    interface HTMLAppBottomSheetElement extends Components.AppBottomSheet, HTMLStencilElement {
    }
    var HTMLAppBottomSheetElement: {
        prototype: HTMLAppBottomSheetElement;
        new (): HTMLAppBottomSheetElement;
    };
    interface HTMLAppBoxShadowElement extends Components.AppBoxShadow, HTMLStencilElement {
    }
    var HTMLAppBoxShadowElement: {
        prototype: HTMLAppBoxShadowElement;
        new (): HTMLAppBoxShadowElement;
    };
    interface HTMLAppBreadcrumbsElement extends Components.AppBreadcrumbs, HTMLStencilElement {
    }
    var HTMLAppBreadcrumbsElement: {
        prototype: HTMLAppBreadcrumbsElement;
        new (): HTMLAppBreadcrumbsElement;
    };
    interface HTMLAppCloseMenuElement extends Components.AppCloseMenu, HTMLStencilElement {
    }
    var HTMLAppCloseMenuElement: {
        prototype: HTMLAppCloseMenuElement;
        new (): HTMLAppCloseMenuElement;
    };
    interface HTMLAppCodeElement extends Components.AppCode, HTMLStencilElement {
    }
    var HTMLAppCodeElement: {
        prototype: HTMLAppCodeElement;
        new (): HTMLAppCodeElement;
    };
    interface HTMLAppCodeEditorElement extends Components.AppCodeEditor, HTMLStencilElement {
    }
    var HTMLAppCodeEditorElement: {
        prototype: HTMLAppCodeEditorElement;
        new (): HTMLAppCodeEditorElement;
    };
    interface HTMLAppCodeLanguagesElement extends Components.AppCodeLanguages, HTMLStencilElement {
    }
    var HTMLAppCodeLanguagesElement: {
        prototype: HTMLAppCodeLanguagesElement;
        new (): HTMLAppCodeLanguagesElement;
    };
    interface HTMLAppColorElement extends Components.AppColor, HTMLStencilElement {
    }
    var HTMLAppColorElement: {
        prototype: HTMLAppColorElement;
        new (): HTMLAppColorElement;
    };
    interface HTMLAppColorChartElement extends Components.AppColorChart, HTMLStencilElement {
    }
    var HTMLAppColorChartElement: {
        prototype: HTMLAppColorChartElement;
        new (): HTMLAppColorChartElement;
    };
    interface HTMLAppColorCodeElement extends Components.AppColorCode, HTMLStencilElement {
    }
    var HTMLAppColorCodeElement: {
        prototype: HTMLAppColorCodeElement;
        new (): HTMLAppColorCodeElement;
    };
    interface HTMLAppColorQrcodeElement extends Components.AppColorQrcode, HTMLStencilElement {
    }
    var HTMLAppColorQrcodeElement: {
        prototype: HTMLAppColorQrcodeElement;
        new (): HTMLAppColorQrcodeElement;
    };
    interface HTMLAppColorSidesElement extends Components.AppColorSides, HTMLStencilElement {
    }
    var HTMLAppColorSidesElement: {
        prototype: HTMLAppColorSidesElement;
        new (): HTMLAppColorSidesElement;
    };
    interface HTMLAppColorTextBackgroundElement extends Components.AppColorTextBackground, HTMLStencilElement {
    }
    var HTMLAppColorTextBackgroundElement: {
        prototype: HTMLAppColorTextBackgroundElement;
        new (): HTMLAppColorTextBackgroundElement;
    };
    interface HTMLAppColorWordCloudElement extends Components.AppColorWordCloud, HTMLStencilElement {
    }
    var HTMLAppColorWordCloudElement: {
        prototype: HTMLAppColorWordCloudElement;
        new (): HTMLAppColorWordCloudElement;
    };
    interface HTMLAppControlElement extends Components.AppControl, HTMLStencilElement {
    }
    var HTMLAppControlElement: {
        prototype: HTMLAppControlElement;
        new (): HTMLAppControlElement;
    };
    interface HTMLAppCopyStyleElement extends Components.AppCopyStyle, HTMLStencilElement {
    }
    var HTMLAppCopyStyleElement: {
        prototype: HTMLAppCopyStyleElement;
        new (): HTMLAppCopyStyleElement;
    };
    interface HTMLAppCreateSlideElement extends Components.AppCreateSlide, HTMLStencilElement {
    }
    var HTMLAppCreateSlideElement: {
        prototype: HTMLAppCreateSlideElement;
        new (): HTMLAppCreateSlideElement;
    };
    interface HTMLAppDeckEditorElement extends Components.AppDeckEditor, HTMLStencilElement {
    }
    var HTMLAppDeckEditorElement: {
        prototype: HTMLAppDeckEditorElement;
        new (): HTMLAppDeckEditorElement;
    };
    interface HTMLAppDeckFontsElement extends Components.AppDeckFonts, HTMLStencilElement {
    }
    var HTMLAppDeckFontsElement: {
        prototype: HTMLAppDeckFontsElement;
        new (): HTMLAppDeckFontsElement;
    };
    interface HTMLAppDeckHeaderFooterElement extends Components.AppDeckHeaderFooter, HTMLStencilElement {
    }
    var HTMLAppDeckHeaderFooterElement: {
        prototype: HTMLAppDeckHeaderFooterElement;
        new (): HTMLAppDeckHeaderFooterElement;
    };
    interface HTMLAppDeckStyleElement extends Components.AppDeckStyle, HTMLStencilElement {
    }
    var HTMLAppDeckStyleElement: {
        prototype: HTMLAppDeckStyleElement;
        new (): HTMLAppDeckStyleElement;
    };
    interface HTMLAppDeckTransitionElement extends Components.AppDeckTransition, HTMLStencilElement {
    }
    var HTMLAppDeckTransitionElement: {
        prototype: HTMLAppDeckTransitionElement;
        new (): HTMLAppDeckTransitionElement;
    };
    interface HTMLAppDemoElement extends Components.AppDemo, HTMLStencilElement {
    }
    var HTMLAppDemoElement: {
        prototype: HTMLAppDemoElement;
        new (): HTMLAppDemoElement;
    };
    interface HTMLAppEditModeElement extends Components.AppEditMode, HTMLStencilElement {
    }
    var HTMLAppEditModeElement: {
        prototype: HTMLAppEditModeElement;
        new (): HTMLAppEditModeElement;
    };
    interface HTMLAppEditSlideElement extends Components.AppEditSlide, HTMLStencilElement {
    }
    var HTMLAppEditSlideElement: {
        prototype: HTMLAppEditSlideElement;
        new (): HTMLAppEditSlideElement;
    };
    interface HTMLAppEditSlideAuthorElement extends Components.AppEditSlideAuthor, HTMLStencilElement {
    }
    var HTMLAppEditSlideAuthorElement: {
        prototype: HTMLAppEditSlideAuthorElement;
        new (): HTMLAppEditSlideAuthorElement;
    };
    interface HTMLAppEditSlideChartElement extends Components.AppEditSlideChart, HTMLStencilElement {
    }
    var HTMLAppEditSlideChartElement: {
        prototype: HTMLAppEditSlideChartElement;
        new (): HTMLAppEditSlideChartElement;
    };
    interface HTMLAppEditSlideQrcodeElement extends Components.AppEditSlideQrcode, HTMLStencilElement {
    }
    var HTMLAppEditSlideQrcodeElement: {
        prototype: HTMLAppEditSlideQrcodeElement;
        new (): HTMLAppEditSlideQrcodeElement;
    };
    interface HTMLAppEditSlideUserElement extends Components.AppEditSlideUser, HTMLStencilElement {
    }
    var HTMLAppEditSlideUserElement: {
        prototype: HTMLAppEditSlideUserElement;
        new (): HTMLAppEditSlideUserElement;
    };
    interface HTMLAppEditorElement extends Components.AppEditor, HTMLStencilElement {
    }
    var HTMLAppEditorElement: {
        prototype: HTMLAppEditorElement;
        new (): HTMLAppEditorElement;
    };
    interface HTMLAppElementStyleElement extends Components.AppElementStyle, HTMLStencilElement {
    }
    var HTMLAppElementStyleElement: {
        prototype: HTMLAppElementStyleElement;
        new (): HTMLAppElementStyleElement;
    };
    interface HTMLAppEmbedElement extends Components.AppEmbed, HTMLStencilElement {
    }
    var HTMLAppEmbedElement: {
        prototype: HTMLAppEmbedElement;
        new (): HTMLAppEmbedElement;
    };
    interface HTMLAppExpansionPanelElement extends Components.AppExpansionPanel, HTMLStencilElement {
    }
    var HTMLAppExpansionPanelElement: {
        prototype: HTMLAppExpansionPanelElement;
        new (): HTMLAppExpansionPanelElement;
    };
    interface HTMLAppFullscreenInfoElement extends Components.AppFullscreenInfo, HTMLStencilElement {
    }
    var HTMLAppFullscreenInfoElement: {
        prototype: HTMLAppFullscreenInfoElement;
        new (): HTMLAppFullscreenInfoElement;
    };
    interface HTMLAppGetHelpElement extends Components.AppGetHelp, HTMLStencilElement {
    }
    var HTMLAppGetHelpElement: {
        prototype: HTMLAppGetHelpElement;
        new (): HTMLAppGetHelpElement;
    };
    interface HTMLAppGifElement extends Components.AppGif, HTMLStencilElement {
    }
    var HTMLAppGifElement: {
        prototype: HTMLAppGifElement;
        new (): HTMLAppGifElement;
    };
    interface HTMLAppImageChoiceElement extends Components.AppImageChoice, HTMLStencilElement {
    }
    var HTMLAppImageChoiceElement: {
        prototype: HTMLAppImageChoiceElement;
        new (): HTMLAppImageChoiceElement;
    };
    interface HTMLAppImageElementElement extends Components.AppImageElement, HTMLStencilElement {
    }
    var HTMLAppImageElementElement: {
        prototype: HTMLAppImageElementElement;
        new (): HTMLAppImageElementElement;
    };
    interface HTMLAppImageHistoryElement extends Components.AppImageHistory, HTMLStencilElement {
    }
    var HTMLAppImageHistoryElement: {
        prototype: HTMLAppImageHistoryElement;
        new (): HTMLAppImageHistoryElement;
    };
    interface HTMLAppImageStyleElement extends Components.AppImageStyle, HTMLStencilElement {
    }
    var HTMLAppImageStyleElement: {
        prototype: HTMLAppImageStyleElement;
        new (): HTMLAppImageStyleElement;
    };
    interface HTMLAppLinksElement extends Components.AppLinks, HTMLStencilElement {
    }
    var HTMLAppLinksElement: {
        prototype: HTMLAppLinksElement;
        new (): HTMLAppLinksElement;
    };
    interface HTMLAppListElement extends Components.AppList, HTMLStencilElement {
    }
    var HTMLAppListElement: {
        prototype: HTMLAppListElement;
        new (): HTMLAppListElement;
    };
    interface HTMLAppLogoElement extends Components.AppLogo, HTMLStencilElement {
    }
    var HTMLAppLogoElement: {
        prototype: HTMLAppLogoElement;
        new (): HTMLAppLogoElement;
    };
    interface HTMLAppMathElement extends Components.AppMath, HTMLStencilElement {
    }
    var HTMLAppMathElement: {
        prototype: HTMLAppMathElement;
        new (): HTMLAppMathElement;
    };
    interface HTMLAppMenuElement extends Components.AppMenu, HTMLStencilElement {
    }
    var HTMLAppMenuElement: {
        prototype: HTMLAppMenuElement;
        new (): HTMLAppMenuElement;
    };
    interface HTMLAppMoreElementActionsElement extends Components.AppMoreElementActions, HTMLStencilElement {
    }
    var HTMLAppMoreElementActionsElement: {
        prototype: HTMLAppMoreElementActionsElement;
        new (): HTMLAppMoreElementActionsElement;
    };
    interface HTMLAppMoreShareOptionsElement extends Components.AppMoreShareOptions, HTMLStencilElement {
    }
    var HTMLAppMoreShareOptionsElement: {
        prototype: HTMLAppMoreShareOptionsElement;
        new (): HTMLAppMoreShareOptionsElement;
    };
    interface HTMLAppNavigationElement extends Components.AppNavigation, HTMLStencilElement {
    }
    var HTMLAppNavigationElement: {
        prototype: HTMLAppNavigationElement;
        new (): HTMLAppNavigationElement;
    };
    interface HTMLAppNavigationEndElement extends Components.AppNavigationEnd, HTMLStencilElement {
    }
    var HTMLAppNavigationEndElement: {
        prototype: HTMLAppNavigationEndElement;
        new (): HTMLAppNavigationEndElement;
    };
    interface HTMLAppNavigationStartElement extends Components.AppNavigationStart, HTMLStencilElement {
    }
    var HTMLAppNavigationStartElement: {
        prototype: HTMLAppNavigationStartElement;
        new (): HTMLAppNavigationStartElement;
    };
    interface HTMLAppNoTemplatesElement extends Components.AppNoTemplates, HTMLStencilElement {
    }
    var HTMLAppNoTemplatesElement: {
        prototype: HTMLAppNoTemplatesElement;
        new (): HTMLAppNoTemplatesElement;
    };
    interface HTMLAppNotesElement extends Components.AppNotes, HTMLStencilElement {
    }
    var HTMLAppNotesElement: {
        prototype: HTMLAppNotesElement;
        new (): HTMLAppNotesElement;
    };
    interface HTMLAppPlaygroundElement extends Components.AppPlayground, HTMLStencilElement {
    }
    var HTMLAppPlaygroundElement: {
        prototype: HTMLAppPlaygroundElement;
        new (): HTMLAppPlaygroundElement;
    };
    interface HTMLAppPlaygroundPlaceholderElement extends Components.AppPlaygroundPlaceholder, HTMLStencilElement {
    }
    var HTMLAppPlaygroundPlaceholderElement: {
        prototype: HTMLAppPlaygroundPlaceholderElement;
        new (): HTMLAppPlaygroundPlaceholderElement;
    };
    interface HTMLAppPollOptionsElement extends Components.AppPollOptions, HTMLStencilElement {
    }
    var HTMLAppPollOptionsElement: {
        prototype: HTMLAppPollOptionsElement;
        new (): HTMLAppPollOptionsElement;
    };
    interface HTMLAppPopoverConfirmElement extends Components.AppPopoverConfirm, HTMLStencilElement {
    }
    var HTMLAppPopoverConfirmElement: {
        prototype: HTMLAppPopoverConfirmElement;
        new (): HTMLAppPopoverConfirmElement;
    };
    interface HTMLAppPresentElement extends Components.AppPresent, HTMLStencilElement {
    }
    var HTMLAppPresentElement: {
        prototype: HTMLAppPresentElement;
        new (): HTMLAppPresentElement;
    };
    interface HTMLAppPublishElement extends Components.AppPublish, HTMLStencilElement {
    }
    var HTMLAppPublishElement: {
        prototype: HTMLAppPublishElement;
        new (): HTMLAppPublishElement;
    };
    interface HTMLAppPublishDoneElement extends Components.AppPublishDone, HTMLStencilElement {
    }
    var HTMLAppPublishDoneElement: {
        prototype: HTMLAppPublishDoneElement;
        new (): HTMLAppPublishDoneElement;
    };
    interface HTMLAppPublishEditElement extends Components.AppPublishEdit, HTMLStencilElement {
    }
    var HTMLAppPublishEditElement: {
        prototype: HTMLAppPublishEditElement;
        new (): HTMLAppPublishEditElement;
    };
    interface HTMLAppPublishTagsElement extends Components.AppPublishTags, HTMLStencilElement {
    }
    var HTMLAppPublishTagsElement: {
        prototype: HTMLAppPublishTagsElement;
        new (): HTMLAppPublishTagsElement;
    };
    interface HTMLAppRandomGifElement extends Components.AppRandomGif, HTMLStencilElement {
    }
    var HTMLAppRandomGifElement: {
        prototype: HTMLAppRandomGifElement;
        new (): HTMLAppRandomGifElement;
    };
    interface HTMLAppRemoteConnectElement extends Components.AppRemoteConnect, HTMLStencilElement {
    }
    var HTMLAppRemoteConnectElement: {
        prototype: HTMLAppRemoteConnectElement;
        new (): HTMLAppRemoteConnectElement;
    };
    interface HTMLAppRemoteRequestElement extends Components.AppRemoteRequest, HTMLStencilElement {
    }
    var HTMLAppRemoteRequestElement: {
        prototype: HTMLAppRemoteRequestElement;
        new (): HTMLAppRemoteRequestElement;
    };
    interface HTMLAppRevealElement extends Components.AppReveal, HTMLStencilElement {
    }
    var HTMLAppRevealElement: {
        prototype: HTMLAppRevealElement;
        new (): HTMLAppRevealElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLAppRootControlElement extends Components.AppRootControl, HTMLStencilElement {
    }
    var HTMLAppRootControlElement: {
        prototype: HTMLAppRootControlElement;
        new (): HTMLAppRootControlElement;
    };
    interface HTMLAppRootViewElement extends Components.AppRootView, HTMLStencilElement {
    }
    var HTMLAppRootViewElement: {
        prototype: HTMLAppRootViewElement;
        new (): HTMLAppRootViewElement;
    };
    interface HTMLAppSelectTargetElementElement extends Components.AppSelectTargetElement, HTMLStencilElement {
    }
    var HTMLAppSelectTargetElementElement: {
        prototype: HTMLAppSelectTargetElementElement;
        new (): HTMLAppSelectTargetElementElement;
    };
    interface HTMLAppShapeElement extends Components.AppShape, HTMLStencilElement {
    }
    var HTMLAppShapeElement: {
        prototype: HTMLAppShapeElement;
        new (): HTMLAppShapeElement;
    };
    interface HTMLAppShareElement extends Components.AppShare, HTMLStencilElement {
    }
    var HTMLAppShareElement: {
        prototype: HTMLAppShareElement;
        new (): HTMLAppShareElement;
    };
    interface HTMLAppShareOptionsElement extends Components.AppShareOptions, HTMLStencilElement {
    }
    var HTMLAppShareOptionsElement: {
        prototype: HTMLAppShareOptionsElement;
        new (): HTMLAppShareOptionsElement;
    };
    interface HTMLAppSlideNavigateElement extends Components.AppSlideNavigate, HTMLStencilElement {
    }
    var HTMLAppSlideNavigateElement: {
        prototype: HTMLAppSlideNavigateElement;
        new (): HTMLAppSlideNavigateElement;
    };
    interface HTMLAppSlidePreviewElement extends Components.AppSlidePreview, HTMLStencilElement {
    }
    var HTMLAppSlidePreviewElement: {
        prototype: HTMLAppSlidePreviewElement;
        new (): HTMLAppSlidePreviewElement;
    };
    interface HTMLAppSlideThumbnailElement extends Components.AppSlideThumbnail, HTMLStencilElement {
    }
    var HTMLAppSlideThumbnailElement: {
        prototype: HTMLAppSlideThumbnailElement;
        new (): HTMLAppSlideThumbnailElement;
    };
    interface HTMLAppSlideWarningElement extends Components.AppSlideWarning, HTMLStencilElement {
    }
    var HTMLAppSlideWarningElement: {
        prototype: HTMLAppSlideWarningElement;
        new (): HTMLAppSlideWarningElement;
    };
    interface HTMLAppSlideWarningInfoElement extends Components.AppSlideWarningInfo, HTMLStencilElement {
    }
    var HTMLAppSlideWarningInfoElement: {
        prototype: HTMLAppSlideWarningInfoElement;
        new (): HTMLAppSlideWarningInfoElement;
    };
    interface HTMLAppSlidesAsideElement extends Components.AppSlidesAside, HTMLStencilElement {
    }
    var HTMLAppSlidesAsideElement: {
        prototype: HTMLAppSlidesAsideElement;
        new (): HTMLAppSlidesAsideElement;
    };
    interface HTMLAppSlotTypeElement extends Components.AppSlotType, HTMLStencilElement {
    }
    var HTMLAppSlotTypeElement: {
        prototype: HTMLAppSlotTypeElement;
        new (): HTMLAppSlotTypeElement;
    };
    interface HTMLAppSpinnerElement extends Components.AppSpinner, HTMLStencilElement {
    }
    var HTMLAppSpinnerElement: {
        prototype: HTMLAppSpinnerElement;
        new (): HTMLAppSpinnerElement;
    };
    interface HTMLAppStorageAdminElement extends Components.AppStorageAdmin, HTMLStencilElement {
    }
    var HTMLAppStorageAdminElement: {
        prototype: HTMLAppStorageAdminElement;
        new (): HTMLAppStorageAdminElement;
    };
    interface HTMLAppStorageDataElement extends Components.AppStorageData, HTMLStencilElement {
    }
    var HTMLAppStorageDataElement: {
        prototype: HTMLAppStorageDataElement;
        new (): HTMLAppStorageDataElement;
    };
    interface HTMLAppStorageFilesElement extends Components.AppStorageFiles, HTMLStencilElement {
    }
    var HTMLAppStorageFilesElement: {
        prototype: HTMLAppStorageFilesElement;
        new (): HTMLAppStorageFilesElement;
    };
    interface HTMLAppStorageImagesElement extends Components.AppStorageImages, HTMLStencilElement {
    }
    var HTMLAppStorageImagesElement: {
        prototype: HTMLAppStorageImagesElement;
        new (): HTMLAppStorageImagesElement;
    };
    interface HTMLAppSyncInfoElement extends Components.AppSyncInfo, HTMLStencilElement {
    }
    var HTMLAppSyncInfoElement: {
        prototype: HTMLAppSyncInfoElement;
        new (): HTMLAppSyncInfoElement;
    };
    interface HTMLAppTemplateShowcaseElement extends Components.AppTemplateShowcase, HTMLStencilElement {
    }
    var HTMLAppTemplateShowcaseElement: {
        prototype: HTMLAppTemplateShowcaseElement;
        new (): HTMLAppTemplateShowcaseElement;
    };
    interface HTMLAppTemplatesChartsElement extends Components.AppTemplatesCharts, HTMLStencilElement {
    }
    var HTMLAppTemplatesChartsElement: {
        prototype: HTMLAppTemplatesChartsElement;
        new (): HTMLAppTemplatesChartsElement;
    };
    interface HTMLAppTemplatesCommunityElement extends Components.AppTemplatesCommunity, HTMLStencilElement {
    }
    var HTMLAppTemplatesCommunityElement: {
        prototype: HTMLAppTemplatesCommunityElement;
        new (): HTMLAppTemplatesCommunityElement;
    };
    interface HTMLAppTemplatesContentElement extends Components.AppTemplatesContent, HTMLStencilElement {
    }
    var HTMLAppTemplatesContentElement: {
        prototype: HTMLAppTemplatesContentElement;
        new (): HTMLAppTemplatesContentElement;
    };
    interface HTMLAppTemplatesDefaultElement extends Components.AppTemplatesDefault, HTMLStencilElement {
    }
    var HTMLAppTemplatesDefaultElement: {
        prototype: HTMLAppTemplatesDefaultElement;
        new (): HTMLAppTemplatesDefaultElement;
    };
    interface HTMLAppTemplatesSplitElement extends Components.AppTemplatesSplit, HTMLStencilElement {
    }
    var HTMLAppTemplatesSplitElement: {
        prototype: HTMLAppTemplatesSplitElement;
        new (): HTMLAppTemplatesSplitElement;
    };
    interface HTMLAppTemplatesTitleElement extends Components.AppTemplatesTitle, HTMLStencilElement {
    }
    var HTMLAppTemplatesTitleElement: {
        prototype: HTMLAppTemplatesTitleElement;
        new (): HTMLAppTemplatesTitleElement;
    };
    interface HTMLAppTextElement extends Components.AppText, HTMLStencilElement {
    }
    var HTMLAppTextElement: {
        prototype: HTMLAppTextElement;
        new (): HTMLAppTextElement;
    };
    interface HTMLAppTransformElementElement extends Components.AppTransformElement, HTMLStencilElement {
    }
    var HTMLAppTransformElementElement: {
        prototype: HTMLAppTransformElementElement;
        new (): HTMLAppTransformElementElement;
    };
    interface HTMLAppTransformSlideElement extends Components.AppTransformSlide, HTMLStencilElement {
    }
    var HTMLAppTransformSlideElement: {
        prototype: HTMLAppTransformSlideElement;
        new (): HTMLAppTransformSlideElement;
    };
    interface HTMLAppUnpublishElement extends Components.AppUnpublish, HTMLStencilElement {
    }
    var HTMLAppUnpublishElement: {
        prototype: HTMLAppUnpublishElement;
        new (): HTMLAppUnpublishElement;
    };
    interface HTMLAppUnsplashElement extends Components.AppUnsplash, HTMLStencilElement {
    }
    var HTMLAppUnsplashElement: {
        prototype: HTMLAppUnsplashElement;
        new (): HTMLAppUnsplashElement;
    };
    interface HTMLAppUserInfoElement extends Components.AppUserInfo, HTMLStencilElement {
    }
    var HTMLAppUserInfoElement: {
        prototype: HTMLAppUserInfoElement;
        new (): HTMLAppUserInfoElement;
    };
    interface HTMLAppWavesElement extends Components.AppWaves, HTMLStencilElement {
    }
    var HTMLAppWavesElement: {
        prototype: HTMLAppWavesElement;
        new (): HTMLAppWavesElement;
    };
    interface HTMLAppYoutubeElement extends Components.AppYoutube, HTMLStencilElement {
    }
    var HTMLAppYoutubeElement: {
        prototype: HTMLAppYoutubeElement;
        new (): HTMLAppYoutubeElement;
    };
    interface HTMLElementTagNameMap {
        "app-action-add-slide": HTMLAppActionAddSlideElement;
        "app-action-busy": HTMLAppActionBusyElement;
        "app-action-help": HTMLAppActionHelpElement;
        "app-action-share": HTMLAppActionShareElement;
        "app-actions-deck": HTMLAppActionsDeckElement;
        "app-actions-deck-editor": HTMLAppActionsDeckEditorElement;
        "app-actions-element": HTMLAppActionsElementElement;
        "app-asset-data": HTMLAppAssetDataElement;
        "app-asset-image": HTMLAppAssetImageElement;
        "app-block": HTMLAppBlockElement;
        "app-border-radius": HTMLAppBorderRadiusElement;
        "app-bottom-sheet": HTMLAppBottomSheetElement;
        "app-box-shadow": HTMLAppBoxShadowElement;
        "app-breadcrumbs": HTMLAppBreadcrumbsElement;
        "app-close-menu": HTMLAppCloseMenuElement;
        "app-code": HTMLAppCodeElement;
        "app-code-editor": HTMLAppCodeEditorElement;
        "app-code-languages": HTMLAppCodeLanguagesElement;
        "app-color": HTMLAppColorElement;
        "app-color-chart": HTMLAppColorChartElement;
        "app-color-code": HTMLAppColorCodeElement;
        "app-color-qrcode": HTMLAppColorQrcodeElement;
        "app-color-sides": HTMLAppColorSidesElement;
        "app-color-text-background": HTMLAppColorTextBackgroundElement;
        "app-color-word-cloud": HTMLAppColorWordCloudElement;
        "app-control": HTMLAppControlElement;
        "app-copy-style": HTMLAppCopyStyleElement;
        "app-create-slide": HTMLAppCreateSlideElement;
        "app-deck-editor": HTMLAppDeckEditorElement;
        "app-deck-fonts": HTMLAppDeckFontsElement;
        "app-deck-header-footer": HTMLAppDeckHeaderFooterElement;
        "app-deck-style": HTMLAppDeckStyleElement;
        "app-deck-transition": HTMLAppDeckTransitionElement;
        "app-demo": HTMLAppDemoElement;
        "app-edit-mode": HTMLAppEditModeElement;
        "app-edit-slide": HTMLAppEditSlideElement;
        "app-edit-slide-author": HTMLAppEditSlideAuthorElement;
        "app-edit-slide-chart": HTMLAppEditSlideChartElement;
        "app-edit-slide-qrcode": HTMLAppEditSlideQrcodeElement;
        "app-edit-slide-user": HTMLAppEditSlideUserElement;
        "app-editor": HTMLAppEditorElement;
        "app-element-style": HTMLAppElementStyleElement;
        "app-embed": HTMLAppEmbedElement;
        "app-expansion-panel": HTMLAppExpansionPanelElement;
        "app-fullscreen-info": HTMLAppFullscreenInfoElement;
        "app-get-help": HTMLAppGetHelpElement;
        "app-gif": HTMLAppGifElement;
        "app-image-choice": HTMLAppImageChoiceElement;
        "app-image-element": HTMLAppImageElementElement;
        "app-image-history": HTMLAppImageHistoryElement;
        "app-image-style": HTMLAppImageStyleElement;
        "app-links": HTMLAppLinksElement;
        "app-list": HTMLAppListElement;
        "app-logo": HTMLAppLogoElement;
        "app-math": HTMLAppMathElement;
        "app-menu": HTMLAppMenuElement;
        "app-more-element-actions": HTMLAppMoreElementActionsElement;
        "app-more-share-options": HTMLAppMoreShareOptionsElement;
        "app-navigation": HTMLAppNavigationElement;
        "app-navigation-end": HTMLAppNavigationEndElement;
        "app-navigation-start": HTMLAppNavigationStartElement;
        "app-no-templates": HTMLAppNoTemplatesElement;
        "app-notes": HTMLAppNotesElement;
        "app-playground": HTMLAppPlaygroundElement;
        "app-playground-placeholder": HTMLAppPlaygroundPlaceholderElement;
        "app-poll-options": HTMLAppPollOptionsElement;
        "app-popover-confirm": HTMLAppPopoverConfirmElement;
        "app-present": HTMLAppPresentElement;
        "app-publish": HTMLAppPublishElement;
        "app-publish-done": HTMLAppPublishDoneElement;
        "app-publish-edit": HTMLAppPublishEditElement;
        "app-publish-tags": HTMLAppPublishTagsElement;
        "app-random-gif": HTMLAppRandomGifElement;
        "app-remote-connect": HTMLAppRemoteConnectElement;
        "app-remote-request": HTMLAppRemoteRequestElement;
        "app-reveal": HTMLAppRevealElement;
        "app-root": HTMLAppRootElement;
        "app-root-control": HTMLAppRootControlElement;
        "app-root-view": HTMLAppRootViewElement;
        "app-select-target-element": HTMLAppSelectTargetElementElement;
        "app-shape": HTMLAppShapeElement;
        "app-share": HTMLAppShareElement;
        "app-share-options": HTMLAppShareOptionsElement;
        "app-slide-navigate": HTMLAppSlideNavigateElement;
        "app-slide-preview": HTMLAppSlidePreviewElement;
        "app-slide-thumbnail": HTMLAppSlideThumbnailElement;
        "app-slide-warning": HTMLAppSlideWarningElement;
        "app-slide-warning-info": HTMLAppSlideWarningInfoElement;
        "app-slides-aside": HTMLAppSlidesAsideElement;
        "app-slot-type": HTMLAppSlotTypeElement;
        "app-spinner": HTMLAppSpinnerElement;
        "app-storage-admin": HTMLAppStorageAdminElement;
        "app-storage-data": HTMLAppStorageDataElement;
        "app-storage-files": HTMLAppStorageFilesElement;
        "app-storage-images": HTMLAppStorageImagesElement;
        "app-sync-info": HTMLAppSyncInfoElement;
        "app-template-showcase": HTMLAppTemplateShowcaseElement;
        "app-templates-charts": HTMLAppTemplatesChartsElement;
        "app-templates-community": HTMLAppTemplatesCommunityElement;
        "app-templates-content": HTMLAppTemplatesContentElement;
        "app-templates-default": HTMLAppTemplatesDefaultElement;
        "app-templates-split": HTMLAppTemplatesSplitElement;
        "app-templates-title": HTMLAppTemplatesTitleElement;
        "app-text": HTMLAppTextElement;
        "app-transform-element": HTMLAppTransformElementElement;
        "app-transform-slide": HTMLAppTransformSlideElement;
        "app-unpublish": HTMLAppUnpublishElement;
        "app-unsplash": HTMLAppUnsplashElement;
        "app-user-info": HTMLAppUserInfoElement;
        "app-waves": HTMLAppWavesElement;
        "app-youtube": HTMLAppYoutubeElement;
    }
}
declare namespace LocalJSX {
    interface AppActionAddSlide {
        "onAddSlide"?: (event: CustomEvent<JSX.IntrinsicElements>) => void;
        "popoverCssClass"?: string;
        "slidesLength"?: number | undefined;
    }
    interface AppActionBusy {
        "iconName"?: string;
        "onActionReady"?: (event: CustomEvent<UIEvent>) => void;
    }
    interface AppActionHelp {
        "link"?: boolean;
        "onHelpSelected"?: (event: CustomEvent<void>) => void;
    }
    interface AppActionShare {
        "onActionPublish"?: (event: CustomEvent<void>) => void;
        "onOpenEmbed"?: (event: CustomEvent<void>) => void;
    }
    interface AppActionsDeck {
        "animatePrevNextSlide"?: EventEmitter;
        "deckDidChange"?: EventEmitter;
        "fullscreen"?: boolean;
        "onSelectDeck"?: (event: CustomEvent<void>) => void;
        "onStepTo"?: (event: CustomEvent<HTMLElement | undefined>) => void;
        "slides"?: JSX.IntrinsicElements[];
        "toggleFullScreen"?: EventEmitter;
    }
    interface AppActionsDeckEditor {
        "fullscreen"?: boolean;
        "onAnimatePrevNextSlide"?: (event: CustomEvent<boolean>) => void;
        "onBlockSlide"?: (event: CustomEvent<boolean>) => void;
        "onDeckDidChange"?: (event: CustomEvent<HTMLElement>) => void;
        "onElementFocus"?: (event: CustomEvent<HTMLElement>) => void;
        "onPresenting"?: (event: CustomEvent<boolean>) => void;
        "onSlideCopy"?: (event: CustomEvent<HTMLElement>) => void;
        "onSlideTransform"?: (event: CustomEvent<JSX.IntrinsicElements>) => void;
        "onToggleFullScreen"?: (event: CustomEvent<void>) => void;
        "slideNumber"?: number;
        "slides"?: JSX.IntrinsicElements[];
    }
    interface AppActionsElement {
        "elementFocus"?: EventEmitter;
        "onBlockSlide"?: (event: CustomEvent<boolean>) => void;
        "onCodeDidChange"?: (event: CustomEvent<HTMLElement>) => void;
        "onImgDidChange"?: (event: CustomEvent<HTMLElement>) => void;
        "onMathDidChange"?: (event: CustomEvent<HTMLElement>) => void;
        "onNotesDidChange"?: (event: CustomEvent<HTMLElement>) => void;
        "onResetted"?: (event: CustomEvent<void>) => void;
        "onSignIn"?: (event: CustomEvent<void>) => void;
        "onSlideDelete"?: (event: CustomEvent<HTMLElement>) => void;
        "onSlideDidChange"?: (event: CustomEvent<HTMLElement>) => void;
        "slideCopy"?: EventEmitter;
        "slideTransform"?: EventEmitter;
    }
    interface AppAssetData {
        "data": StorageFile;
    }
    interface AppAssetImage {
        "image": UnsplashPhoto | TenorGif | StorageFile | Waves | TenorCategory;
    }
    interface AppBlock {
        "onBlockChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: SelectedTarget;
    }
    interface AppBorderRadius {
        "onBorderRadiusDidChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: SelectedTarget;
    }
    interface AppBottomSheet {
        "onSheetChanged"?: (event: CustomEvent<'open' | 'close'>) => void;
    }
    interface AppBoxShadow {
        "onBoxShadowDidChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: SelectedTarget;
    }
    interface AppBreadcrumbs {
        "onStepTo"?: (event: CustomEvent<HTMLElement | undefined>) => void;
        "slideNumber"?: number;
    }
    interface AppCloseMenu {
        "onClose"?: (event: CustomEvent<void>) => void;
    }
    interface AppCode {
        "codeDidChange"?: EventEmitter<HTMLElement> | undefined;
        "selectedTarget"?: HTMLElement;
    }
    interface AppCodeEditor {
        "code"?: string;
        "options"?: MonacoEditorOptions;
    }
    interface AppCodeLanguages {
        "codeDidChange"?: EventEmitter<HTMLElement> | undefined;
        "currentLanguage"?: PrismLanguage | undefined;
        "selectedTarget"?: HTMLElement;
    }
    interface AppColor {
        "defaultColor"?: string;
        "initColor"?: () => Promise<InitStyleColor>;
        "onColorDidChange"?: (event: CustomEvent<string>) => void;
        "onResetColor"?: (event: CustomEvent<void>) => void;
    }
    interface AppColorChart {
        "onColorChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: HTMLElement;
    }
    interface AppColorCode {
        "onCodeDidChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: HTMLElement;
    }
    interface AppColorQrcode {
        "onColorChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: HTMLElement;
    }
    interface AppColorSides {
        "onColorChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: HTMLElement;
        "template"?: 'split' | 'author';
    }
    interface AppColorTextBackground {
        "colorType"?: 'text' | 'background';
        "deck"?: boolean;
        "onColorChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: HTMLElement;
        "slide"?: boolean;
    }
    interface AppColorWordCloud {
        "onWordCloudDidChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: HTMLElement;
    }
    interface AppControl {
    }
    interface AppCopyStyle {
        "selectedTarget"?: HTMLElement;
    }
    interface AppCreateSlide {
        "onSignIn"?: (event: CustomEvent<void>) => void;
    }
    interface AppDeckEditor {
        "autoConnect"?: boolean;
    }
    interface AppDeckFonts {
        "deckElement"?: HTMLElement;
        "onFontsChange"?: (event: CustomEvent<void>) => void;
    }
    interface AppDeckHeaderFooter {
        "deckDidChange"?: EventEmitter<HTMLElement>;
        "deckElement"?: HTMLElement;
        "onNavigateSettings"?: (event: CustomEvent<void>) => void;
        "onNavigateSignIn"?: (event: CustomEvent<void>) => void;
    }
    interface AppDeckStyle {
        "deckDidChange"?: EventEmitter<HTMLElement>;
        "onBlockSlide"?: (event: CustomEvent<boolean>) => void;
        "onSignIn"?: (event: CustomEvent<void>) => void;
    }
    interface AppDeckTransition {
        "deckElement"?: HTMLDeckgoDeckElement;
        "onDeckNeedChange"?: (event: CustomEvent<DeckAction>) => void;
        "onTransitionChange"?: (event: CustomEvent<void>) => void;
    }
    interface AppDemo {
        "selectedTarget"?: HTMLElement;
    }
    interface AppEditMode {
    }
    interface AppEditSlide {
        "selectedTarget"?: SelectedTarget;
        "slideDidChange"?: EventEmitter<HTMLElement>;
    }
    interface AppEditSlideAuthor {
        "selectedTarget"?: HTMLElement;
        "slideDidChange"?: EventEmitter<HTMLElement>;
    }
    interface AppEditSlideChart {
        "onAction"?: (event: CustomEvent<EditAction>) => void;
        "selectedTarget"?: HTMLElement;
        "slideDidChange"?: EventEmitter<HTMLElement>;
    }
    interface AppEditSlideQrcode {
        "onAction"?: (event: CustomEvent<EditAction>) => void;
        "selectedTarget"?: HTMLElement;
        "slideDidChange"?: EventEmitter<HTMLElement>;
    }
    interface AppEditSlideUser {
        "selectedTarget"?: SelectedTarget;
        "slideDidChange"?: EventEmitter<HTMLElement>;
    }
    interface AppEditor {
        "autoConnect"?: boolean;
    }
    interface AppElementStyle {
        "imageHelper"?: ImageHelper;
        "imgDidChange"?: EventEmitter<HTMLElement>;
        "onOptionsDidChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: SelectedTarget;
    }
    interface AppEmbed {
    }
    interface AppExpansionPanel {
        "expanded"?: Expanded;
        "expander"?: boolean;
        "onExpansion"?: (event: CustomEvent<Expanded>) => void;
    }
    interface AppFullscreenInfo {
    }
    interface AppGetHelp {
    }
    interface AppGif {
    }
    interface AppImageChoice {
        "deck"?: boolean;
        "deleteBackground"?: boolean;
        "onAction"?: (event: CustomEvent<ImageAction>) => void;
        "selectedTarget"?: HTMLElement;
        "slide"?: boolean;
    }
    interface AppImageElement {
        "selectedTarget"?: HTMLElement;
        "slide"?: boolean;
    }
    interface AppImageHistory {
        "deck"?: boolean;
        "onSelectImage"?: (event: CustomEvent<UnsplashPhoto | TenorGif | StorageFile | Waves>) => void;
        "slide"?: boolean;
    }
    interface AppImageStyle {
        "onImgDidChange"?: (event: CustomEvent<HTMLElement>) => void;
        "selectedTarget"?: HTMLElement;
    }
    interface AppLinks {
    }
    interface AppList {
        "onListStyleChanged"?: (event: CustomEvent<ListStyle>) => void;
        "onToggleList"?: (event: CustomEvent<SlotType.OL | SlotType.UL>) => void;
        "selectedTarget"?: HTMLElement;
    }
    interface AppLogo {
    }
    interface AppMath {
        "mathDidChange"?: EventEmitter<HTMLElement>;
        "selectedTarget"?: HTMLElement;
    }
    interface AppMenu {
    }
    interface AppMoreElementActions {
        "clone"?: boolean;
        "images"?: boolean;
        "notes"?: boolean;
        "transform"?: boolean;
    }
    interface AppMoreShareOptions {
    }
    interface AppNavigation {
        "actions"?: 'all' | 'none' | 'editor-less';
    }
    interface AppNavigationEnd {
        "editorActions"?: boolean;
    }
    interface AppNavigationStart {
    }
    interface AppNoTemplates {
    }
    interface AppNotes {
        "selectedTarget"?: HTMLElement;
    }
    interface AppPlayground {
        "selectedTarget"?: HTMLElement;
    }
    interface AppPlaygroundPlaceholder {
    }
    interface AppPollOptions {
        "selectedTarget"?: HTMLElement;
        "slideDidChange"?: EventEmitter<HTMLElement>;
    }
    interface AppPopoverConfirm {
        "onConfirm"?: (event: CustomEvent<boolean>) => void;
    }
    interface AppPresent {
        "fullscreen"?: boolean;
        "onToggleFullScreen"?: (event: CustomEvent<void>) => void;
    }
    interface AppPublish {
    }
    interface AppPublishDone {
        "publishedUrl"?: string;
    }
    interface AppPublishEdit {
        "onPublished"?: (event: CustomEvent<string>) => void;
    }
    interface AppPublishTags {
        "disableRemove"?: boolean;
        "onRemoveTag"?: (event: CustomEvent<string>) => void;
        "tags"?: string[];
    }
    interface AppRandomGif {
        "keyword"?: string;
    }
    interface AppRemoteConnect {
    }
    interface AppRemoteRequest {
    }
    interface AppReveal {
        "onToggleReveal"?: (event: CustomEvent<boolean>) => void;
        "selectedTarget"?: HTMLElement;
    }
    interface AppRoot {
    }
    interface AppRootControl {
    }
    interface AppRootView {
    }
    interface AppSelectTargetElement {
        "chart"?: boolean;
        "code"?: boolean;
        "headerFooter"?: boolean;
        "image"?: boolean;
        "onApplyTo"?: (event: CustomEvent<TargetElement>) => void;
        "qrCode"?: boolean;
        "sides"?: boolean;
        "slide"?: boolean;
        "textTarget"?: boolean;
        "transition"?: boolean;
        "wordCloud"?: boolean;
    }
    interface AppShape {
        "selectedTarget"?: HTMLElement;
    }
    interface AppShare {
    }
    interface AppShareOptions {
        "onSelectedOption"?: (event: CustomEvent<MoreAction>) => void;
    }
    interface AppSlideNavigate {
        "onReorder"?: (event: CustomEvent<ItemReorderEventDetail>) => void;
    }
    interface AppSlidePreview {
        "deckRef": HTMLDeckgoDeckElement;
        "onPreviewAttached"?: (event: CustomEvent<void>) => void;
    }
    interface AppSlideThumbnail {
        "deck"?: HTMLDeckgoDeckElement;
        "slide"?: HTMLElement;
    }
    interface AppSlideWarning {
    }
    interface AppSlideWarningInfo {
        "lowContrast"?: boolean;
        "overflow"?: boolean;
    }
    interface AppSlidesAside {
        "activeIndex"?: number;
        "deckRef": HTMLDeckgoDeckElement;
        "onReorder"?: (event: CustomEvent<ItemReorderEventDetail>) => void;
        "onStepTo"?: (event: CustomEvent<HTMLElement | undefined>) => void;
    }
    interface AppSlotType {
        "onSelectType"?: (event: CustomEvent<SlotType | null>) => void;
        "selectedTarget"?: HTMLElement | undefined;
        "skip"?: boolean;
        "slotTypes"?: SlotType[] | undefined;
    }
    interface AppSpinner {
    }
    interface AppStorageAdmin {
        "onFileDeleted"?: (event: CustomEvent<string>) => void;
        "storageFile": StorageFile;
    }
    interface AppStorageData {
    }
    interface AppStorageFiles {
        "admin"?: boolean;
        "folder": 'data' | 'images';
        "onSelectAsset"?: (event: CustomEvent<StorageFile>) => void;
    }
    interface AppStorageImages {
    }
    interface AppSyncInfo {
    }
    interface AppTemplateShowcase {
        "author"?: boolean;
        "editable"?: boolean;
        "template"?: Template;
    }
    interface AppTemplatesCharts {
        "onSelectedTemplate"?: (event: CustomEvent<{template: SlideTemplate; attributes: SlideAttributes}>) => void;
    }
    interface AppTemplatesCommunity {
        "onSelectedTemplate"?: (event: CustomEvent<Template>) => void;
    }
    interface AppTemplatesContent {
        "highlight"?: boolean;
        "highlightIndex"?: number | undefined;
        "selected"?: boolean;
    }
    interface AppTemplatesDefault {
        "onAddSlideAspectRatio"?: (event: CustomEvent<void>) => void;
        "onAddSlideAuthor"?: (event: CustomEvent<void>) => void;
        "onAddSlideQRCode"?: (event: CustomEvent<void>) => void;
        "onComposeTemplate"?: (event: CustomEvent<InitTemplate>) => void;
        "onSelectCharts"?: (event: CustomEvent<void>) => void;
        "onSelectedTemplate"?: (event: CustomEvent<{template: SlideTemplate | Template; attributes?: SlideAttributes}>) => void;
    }
    interface AppTemplatesSplit {
        "highlight"?: boolean;
        "highlightIndex"?: number | undefined;
        "selected"?: boolean;
        "vertical"?: boolean;
    }
    interface AppTemplatesTitle {
        "highlight"?: boolean;
        "highlightIndex"?: number | undefined;
        "selected"?: boolean;
    }
    interface AppText {
        "onTextDidChange"?: (event: CustomEvent<void>) => void;
        "selectedTarget"?: SelectedTarget;
    }
    interface AppTransformElement {
        "selectedTarget"?: HTMLElement;
    }
    interface AppTransformSlide {
        "selectedTarget"?: HTMLElement;
    }
    interface AppUnpublish {
    }
    interface AppUnsplash {
    }
    interface AppUserInfo {
        "displayAvatar"?: boolean;
    }
    interface AppWaves {
    }
    interface AppYoutube {
        "selectedTarget"?: HTMLElement;
    }
    interface IntrinsicElements {
        "app-action-add-slide": AppActionAddSlide;
        "app-action-busy": AppActionBusy;
        "app-action-help": AppActionHelp;
        "app-action-share": AppActionShare;
        "app-actions-deck": AppActionsDeck;
        "app-actions-deck-editor": AppActionsDeckEditor;
        "app-actions-element": AppActionsElement;
        "app-asset-data": AppAssetData;
        "app-asset-image": AppAssetImage;
        "app-block": AppBlock;
        "app-border-radius": AppBorderRadius;
        "app-bottom-sheet": AppBottomSheet;
        "app-box-shadow": AppBoxShadow;
        "app-breadcrumbs": AppBreadcrumbs;
        "app-close-menu": AppCloseMenu;
        "app-code": AppCode;
        "app-code-editor": AppCodeEditor;
        "app-code-languages": AppCodeLanguages;
        "app-color": AppColor;
        "app-color-chart": AppColorChart;
        "app-color-code": AppColorCode;
        "app-color-qrcode": AppColorQrcode;
        "app-color-sides": AppColorSides;
        "app-color-text-background": AppColorTextBackground;
        "app-color-word-cloud": AppColorWordCloud;
        "app-control": AppControl;
        "app-copy-style": AppCopyStyle;
        "app-create-slide": AppCreateSlide;
        "app-deck-editor": AppDeckEditor;
        "app-deck-fonts": AppDeckFonts;
        "app-deck-header-footer": AppDeckHeaderFooter;
        "app-deck-style": AppDeckStyle;
        "app-deck-transition": AppDeckTransition;
        "app-demo": AppDemo;
        "app-edit-mode": AppEditMode;
        "app-edit-slide": AppEditSlide;
        "app-edit-slide-author": AppEditSlideAuthor;
        "app-edit-slide-chart": AppEditSlideChart;
        "app-edit-slide-qrcode": AppEditSlideQrcode;
        "app-edit-slide-user": AppEditSlideUser;
        "app-editor": AppEditor;
        "app-element-style": AppElementStyle;
        "app-embed": AppEmbed;
        "app-expansion-panel": AppExpansionPanel;
        "app-fullscreen-info": AppFullscreenInfo;
        "app-get-help": AppGetHelp;
        "app-gif": AppGif;
        "app-image-choice": AppImageChoice;
        "app-image-element": AppImageElement;
        "app-image-history": AppImageHistory;
        "app-image-style": AppImageStyle;
        "app-links": AppLinks;
        "app-list": AppList;
        "app-logo": AppLogo;
        "app-math": AppMath;
        "app-menu": AppMenu;
        "app-more-element-actions": AppMoreElementActions;
        "app-more-share-options": AppMoreShareOptions;
        "app-navigation": AppNavigation;
        "app-navigation-end": AppNavigationEnd;
        "app-navigation-start": AppNavigationStart;
        "app-no-templates": AppNoTemplates;
        "app-notes": AppNotes;
        "app-playground": AppPlayground;
        "app-playground-placeholder": AppPlaygroundPlaceholder;
        "app-poll-options": AppPollOptions;
        "app-popover-confirm": AppPopoverConfirm;
        "app-present": AppPresent;
        "app-publish": AppPublish;
        "app-publish-done": AppPublishDone;
        "app-publish-edit": AppPublishEdit;
        "app-publish-tags": AppPublishTags;
        "app-random-gif": AppRandomGif;
        "app-remote-connect": AppRemoteConnect;
        "app-remote-request": AppRemoteRequest;
        "app-reveal": AppReveal;
        "app-root": AppRoot;
        "app-root-control": AppRootControl;
        "app-root-view": AppRootView;
        "app-select-target-element": AppSelectTargetElement;
        "app-shape": AppShape;
        "app-share": AppShare;
        "app-share-options": AppShareOptions;
        "app-slide-navigate": AppSlideNavigate;
        "app-slide-preview": AppSlidePreview;
        "app-slide-thumbnail": AppSlideThumbnail;
        "app-slide-warning": AppSlideWarning;
        "app-slide-warning-info": AppSlideWarningInfo;
        "app-slides-aside": AppSlidesAside;
        "app-slot-type": AppSlotType;
        "app-spinner": AppSpinner;
        "app-storage-admin": AppStorageAdmin;
        "app-storage-data": AppStorageData;
        "app-storage-files": AppStorageFiles;
        "app-storage-images": AppStorageImages;
        "app-sync-info": AppSyncInfo;
        "app-template-showcase": AppTemplateShowcase;
        "app-templates-charts": AppTemplatesCharts;
        "app-templates-community": AppTemplatesCommunity;
        "app-templates-content": AppTemplatesContent;
        "app-templates-default": AppTemplatesDefault;
        "app-templates-split": AppTemplatesSplit;
        "app-templates-title": AppTemplatesTitle;
        "app-text": AppText;
        "app-transform-element": AppTransformElement;
        "app-transform-slide": AppTransformSlide;
        "app-unpublish": AppUnpublish;
        "app-unsplash": AppUnsplash;
        "app-user-info": AppUserInfo;
        "app-waves": AppWaves;
        "app-youtube": AppYoutube;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-action-add-slide": LocalJSX.AppActionAddSlide & JSXBase.HTMLAttributes<HTMLAppActionAddSlideElement>;
            "app-action-busy": LocalJSX.AppActionBusy & JSXBase.HTMLAttributes<HTMLAppActionBusyElement>;
            "app-action-help": LocalJSX.AppActionHelp & JSXBase.HTMLAttributes<HTMLAppActionHelpElement>;
            "app-action-share": LocalJSX.AppActionShare & JSXBase.HTMLAttributes<HTMLAppActionShareElement>;
            "app-actions-deck": LocalJSX.AppActionsDeck & JSXBase.HTMLAttributes<HTMLAppActionsDeckElement>;
            "app-actions-deck-editor": LocalJSX.AppActionsDeckEditor & JSXBase.HTMLAttributes<HTMLAppActionsDeckEditorElement>;
            "app-actions-element": LocalJSX.AppActionsElement & JSXBase.HTMLAttributes<HTMLAppActionsElementElement>;
            "app-asset-data": LocalJSX.AppAssetData & JSXBase.HTMLAttributes<HTMLAppAssetDataElement>;
            "app-asset-image": LocalJSX.AppAssetImage & JSXBase.HTMLAttributes<HTMLAppAssetImageElement>;
            "app-block": LocalJSX.AppBlock & JSXBase.HTMLAttributes<HTMLAppBlockElement>;
            "app-border-radius": LocalJSX.AppBorderRadius & JSXBase.HTMLAttributes<HTMLAppBorderRadiusElement>;
            "app-bottom-sheet": LocalJSX.AppBottomSheet & JSXBase.HTMLAttributes<HTMLAppBottomSheetElement>;
            "app-box-shadow": LocalJSX.AppBoxShadow & JSXBase.HTMLAttributes<HTMLAppBoxShadowElement>;
            "app-breadcrumbs": LocalJSX.AppBreadcrumbs & JSXBase.HTMLAttributes<HTMLAppBreadcrumbsElement>;
            "app-close-menu": LocalJSX.AppCloseMenu & JSXBase.HTMLAttributes<HTMLAppCloseMenuElement>;
            "app-code": LocalJSX.AppCode & JSXBase.HTMLAttributes<HTMLAppCodeElement>;
            "app-code-editor": LocalJSX.AppCodeEditor & JSXBase.HTMLAttributes<HTMLAppCodeEditorElement>;
            "app-code-languages": LocalJSX.AppCodeLanguages & JSXBase.HTMLAttributes<HTMLAppCodeLanguagesElement>;
            "app-color": LocalJSX.AppColor & JSXBase.HTMLAttributes<HTMLAppColorElement>;
            "app-color-chart": LocalJSX.AppColorChart & JSXBase.HTMLAttributes<HTMLAppColorChartElement>;
            "app-color-code": LocalJSX.AppColorCode & JSXBase.HTMLAttributes<HTMLAppColorCodeElement>;
            "app-color-qrcode": LocalJSX.AppColorQrcode & JSXBase.HTMLAttributes<HTMLAppColorQrcodeElement>;
            "app-color-sides": LocalJSX.AppColorSides & JSXBase.HTMLAttributes<HTMLAppColorSidesElement>;
            "app-color-text-background": LocalJSX.AppColorTextBackground & JSXBase.HTMLAttributes<HTMLAppColorTextBackgroundElement>;
            "app-color-word-cloud": LocalJSX.AppColorWordCloud & JSXBase.HTMLAttributes<HTMLAppColorWordCloudElement>;
            "app-control": LocalJSX.AppControl & JSXBase.HTMLAttributes<HTMLAppControlElement>;
            "app-copy-style": LocalJSX.AppCopyStyle & JSXBase.HTMLAttributes<HTMLAppCopyStyleElement>;
            "app-create-slide": LocalJSX.AppCreateSlide & JSXBase.HTMLAttributes<HTMLAppCreateSlideElement>;
            "app-deck-editor": LocalJSX.AppDeckEditor & JSXBase.HTMLAttributes<HTMLAppDeckEditorElement>;
            "app-deck-fonts": LocalJSX.AppDeckFonts & JSXBase.HTMLAttributes<HTMLAppDeckFontsElement>;
            "app-deck-header-footer": LocalJSX.AppDeckHeaderFooter & JSXBase.HTMLAttributes<HTMLAppDeckHeaderFooterElement>;
            "app-deck-style": LocalJSX.AppDeckStyle & JSXBase.HTMLAttributes<HTMLAppDeckStyleElement>;
            "app-deck-transition": LocalJSX.AppDeckTransition & JSXBase.HTMLAttributes<HTMLAppDeckTransitionElement>;
            "app-demo": LocalJSX.AppDemo & JSXBase.HTMLAttributes<HTMLAppDemoElement>;
            "app-edit-mode": LocalJSX.AppEditMode & JSXBase.HTMLAttributes<HTMLAppEditModeElement>;
            "app-edit-slide": LocalJSX.AppEditSlide & JSXBase.HTMLAttributes<HTMLAppEditSlideElement>;
            "app-edit-slide-author": LocalJSX.AppEditSlideAuthor & JSXBase.HTMLAttributes<HTMLAppEditSlideAuthorElement>;
            "app-edit-slide-chart": LocalJSX.AppEditSlideChart & JSXBase.HTMLAttributes<HTMLAppEditSlideChartElement>;
            "app-edit-slide-qrcode": LocalJSX.AppEditSlideQrcode & JSXBase.HTMLAttributes<HTMLAppEditSlideQrcodeElement>;
            "app-edit-slide-user": LocalJSX.AppEditSlideUser & JSXBase.HTMLAttributes<HTMLAppEditSlideUserElement>;
            "app-editor": LocalJSX.AppEditor & JSXBase.HTMLAttributes<HTMLAppEditorElement>;
            "app-element-style": LocalJSX.AppElementStyle & JSXBase.HTMLAttributes<HTMLAppElementStyleElement>;
            "app-embed": LocalJSX.AppEmbed & JSXBase.HTMLAttributes<HTMLAppEmbedElement>;
            "app-expansion-panel": LocalJSX.AppExpansionPanel & JSXBase.HTMLAttributes<HTMLAppExpansionPanelElement>;
            "app-fullscreen-info": LocalJSX.AppFullscreenInfo & JSXBase.HTMLAttributes<HTMLAppFullscreenInfoElement>;
            "app-get-help": LocalJSX.AppGetHelp & JSXBase.HTMLAttributes<HTMLAppGetHelpElement>;
            "app-gif": LocalJSX.AppGif & JSXBase.HTMLAttributes<HTMLAppGifElement>;
            "app-image-choice": LocalJSX.AppImageChoice & JSXBase.HTMLAttributes<HTMLAppImageChoiceElement>;
            "app-image-element": LocalJSX.AppImageElement & JSXBase.HTMLAttributes<HTMLAppImageElementElement>;
            "app-image-history": LocalJSX.AppImageHistory & JSXBase.HTMLAttributes<HTMLAppImageHistoryElement>;
            "app-image-style": LocalJSX.AppImageStyle & JSXBase.HTMLAttributes<HTMLAppImageStyleElement>;
            "app-links": LocalJSX.AppLinks & JSXBase.HTMLAttributes<HTMLAppLinksElement>;
            "app-list": LocalJSX.AppList & JSXBase.HTMLAttributes<HTMLAppListElement>;
            "app-logo": LocalJSX.AppLogo & JSXBase.HTMLAttributes<HTMLAppLogoElement>;
            "app-math": LocalJSX.AppMath & JSXBase.HTMLAttributes<HTMLAppMathElement>;
            "app-menu": LocalJSX.AppMenu & JSXBase.HTMLAttributes<HTMLAppMenuElement>;
            "app-more-element-actions": LocalJSX.AppMoreElementActions & JSXBase.HTMLAttributes<HTMLAppMoreElementActionsElement>;
            "app-more-share-options": LocalJSX.AppMoreShareOptions & JSXBase.HTMLAttributes<HTMLAppMoreShareOptionsElement>;
            "app-navigation": LocalJSX.AppNavigation & JSXBase.HTMLAttributes<HTMLAppNavigationElement>;
            "app-navigation-end": LocalJSX.AppNavigationEnd & JSXBase.HTMLAttributes<HTMLAppNavigationEndElement>;
            "app-navigation-start": LocalJSX.AppNavigationStart & JSXBase.HTMLAttributes<HTMLAppNavigationStartElement>;
            "app-no-templates": LocalJSX.AppNoTemplates & JSXBase.HTMLAttributes<HTMLAppNoTemplatesElement>;
            "app-notes": LocalJSX.AppNotes & JSXBase.HTMLAttributes<HTMLAppNotesElement>;
            "app-playground": LocalJSX.AppPlayground & JSXBase.HTMLAttributes<HTMLAppPlaygroundElement>;
            "app-playground-placeholder": LocalJSX.AppPlaygroundPlaceholder & JSXBase.HTMLAttributes<HTMLAppPlaygroundPlaceholderElement>;
            "app-poll-options": LocalJSX.AppPollOptions & JSXBase.HTMLAttributes<HTMLAppPollOptionsElement>;
            "app-popover-confirm": LocalJSX.AppPopoverConfirm & JSXBase.HTMLAttributes<HTMLAppPopoverConfirmElement>;
            "app-present": LocalJSX.AppPresent & JSXBase.HTMLAttributes<HTMLAppPresentElement>;
            "app-publish": LocalJSX.AppPublish & JSXBase.HTMLAttributes<HTMLAppPublishElement>;
            "app-publish-done": LocalJSX.AppPublishDone & JSXBase.HTMLAttributes<HTMLAppPublishDoneElement>;
            "app-publish-edit": LocalJSX.AppPublishEdit & JSXBase.HTMLAttributes<HTMLAppPublishEditElement>;
            "app-publish-tags": LocalJSX.AppPublishTags & JSXBase.HTMLAttributes<HTMLAppPublishTagsElement>;
            "app-random-gif": LocalJSX.AppRandomGif & JSXBase.HTMLAttributes<HTMLAppRandomGifElement>;
            "app-remote-connect": LocalJSX.AppRemoteConnect & JSXBase.HTMLAttributes<HTMLAppRemoteConnectElement>;
            "app-remote-request": LocalJSX.AppRemoteRequest & JSXBase.HTMLAttributes<HTMLAppRemoteRequestElement>;
            "app-reveal": LocalJSX.AppReveal & JSXBase.HTMLAttributes<HTMLAppRevealElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "app-root-control": LocalJSX.AppRootControl & JSXBase.HTMLAttributes<HTMLAppRootControlElement>;
            "app-root-view": LocalJSX.AppRootView & JSXBase.HTMLAttributes<HTMLAppRootViewElement>;
            "app-select-target-element": LocalJSX.AppSelectTargetElement & JSXBase.HTMLAttributes<HTMLAppSelectTargetElementElement>;
            "app-shape": LocalJSX.AppShape & JSXBase.HTMLAttributes<HTMLAppShapeElement>;
            "app-share": LocalJSX.AppShare & JSXBase.HTMLAttributes<HTMLAppShareElement>;
            "app-share-options": LocalJSX.AppShareOptions & JSXBase.HTMLAttributes<HTMLAppShareOptionsElement>;
            "app-slide-navigate": LocalJSX.AppSlideNavigate & JSXBase.HTMLAttributes<HTMLAppSlideNavigateElement>;
            "app-slide-preview": LocalJSX.AppSlidePreview & JSXBase.HTMLAttributes<HTMLAppSlidePreviewElement>;
            "app-slide-thumbnail": LocalJSX.AppSlideThumbnail & JSXBase.HTMLAttributes<HTMLAppSlideThumbnailElement>;
            "app-slide-warning": LocalJSX.AppSlideWarning & JSXBase.HTMLAttributes<HTMLAppSlideWarningElement>;
            "app-slide-warning-info": LocalJSX.AppSlideWarningInfo & JSXBase.HTMLAttributes<HTMLAppSlideWarningInfoElement>;
            "app-slides-aside": LocalJSX.AppSlidesAside & JSXBase.HTMLAttributes<HTMLAppSlidesAsideElement>;
            "app-slot-type": LocalJSX.AppSlotType & JSXBase.HTMLAttributes<HTMLAppSlotTypeElement>;
            "app-spinner": LocalJSX.AppSpinner & JSXBase.HTMLAttributes<HTMLAppSpinnerElement>;
            "app-storage-admin": LocalJSX.AppStorageAdmin & JSXBase.HTMLAttributes<HTMLAppStorageAdminElement>;
            "app-storage-data": LocalJSX.AppStorageData & JSXBase.HTMLAttributes<HTMLAppStorageDataElement>;
            "app-storage-files": LocalJSX.AppStorageFiles & JSXBase.HTMLAttributes<HTMLAppStorageFilesElement>;
            "app-storage-images": LocalJSX.AppStorageImages & JSXBase.HTMLAttributes<HTMLAppStorageImagesElement>;
            "app-sync-info": LocalJSX.AppSyncInfo & JSXBase.HTMLAttributes<HTMLAppSyncInfoElement>;
            "app-template-showcase": LocalJSX.AppTemplateShowcase & JSXBase.HTMLAttributes<HTMLAppTemplateShowcaseElement>;
            "app-templates-charts": LocalJSX.AppTemplatesCharts & JSXBase.HTMLAttributes<HTMLAppTemplatesChartsElement>;
            "app-templates-community": LocalJSX.AppTemplatesCommunity & JSXBase.HTMLAttributes<HTMLAppTemplatesCommunityElement>;
            "app-templates-content": LocalJSX.AppTemplatesContent & JSXBase.HTMLAttributes<HTMLAppTemplatesContentElement>;
            "app-templates-default": LocalJSX.AppTemplatesDefault & JSXBase.HTMLAttributes<HTMLAppTemplatesDefaultElement>;
            "app-templates-split": LocalJSX.AppTemplatesSplit & JSXBase.HTMLAttributes<HTMLAppTemplatesSplitElement>;
            "app-templates-title": LocalJSX.AppTemplatesTitle & JSXBase.HTMLAttributes<HTMLAppTemplatesTitleElement>;
            "app-text": LocalJSX.AppText & JSXBase.HTMLAttributes<HTMLAppTextElement>;
            "app-transform-element": LocalJSX.AppTransformElement & JSXBase.HTMLAttributes<HTMLAppTransformElementElement>;
            "app-transform-slide": LocalJSX.AppTransformSlide & JSXBase.HTMLAttributes<HTMLAppTransformSlideElement>;
            "app-unpublish": LocalJSX.AppUnpublish & JSXBase.HTMLAttributes<HTMLAppUnpublishElement>;
            "app-unsplash": LocalJSX.AppUnsplash & JSXBase.HTMLAttributes<HTMLAppUnsplashElement>;
            "app-user-info": LocalJSX.AppUserInfo & JSXBase.HTMLAttributes<HTMLAppUserInfoElement>;
            "app-waves": LocalJSX.AppWaves & JSXBase.HTMLAttributes<HTMLAppWavesElement>;
            "app-youtube": LocalJSX.AppYoutube & JSXBase.HTMLAttributes<HTMLAppYoutubeElement>;
        }
    }
}
