/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppBottomSheet {
    }
    interface AppDraw {
        "height": number;
        "heightOffset": number;
        "moveDraw": (leftOffset: number, transitionDuration: string) => Promise<void>;
        "slides": number;
        "width": number;
        "widthOffset": number;
    }
    interface AppLogo {
    }
    interface AppRemote {
        "room": string;
    }
    interface AppRemoteSlidePicker {
    }
    interface AppRemoteViewer {
    }
    interface AppRootControl {
    }
    interface AppRootView {
    }
}
declare global {
    interface HTMLAppBottomSheetElement extends Components.AppBottomSheet, HTMLStencilElement {
    }
    var HTMLAppBottomSheetElement: {
        prototype: HTMLAppBottomSheetElement;
        new (): HTMLAppBottomSheetElement;
    };
    interface HTMLAppDrawElement extends Components.AppDraw, HTMLStencilElement {
    }
    var HTMLAppDrawElement: {
        prototype: HTMLAppDrawElement;
        new (): HTMLAppDrawElement;
    };
    interface HTMLAppLogoElement extends Components.AppLogo, HTMLStencilElement {
    }
    var HTMLAppLogoElement: {
        prototype: HTMLAppLogoElement;
        new (): HTMLAppLogoElement;
    };
    interface HTMLAppRemoteElement extends Components.AppRemote, HTMLStencilElement {
    }
    var HTMLAppRemoteElement: {
        prototype: HTMLAppRemoteElement;
        new (): HTMLAppRemoteElement;
    };
    interface HTMLAppRemoteSlidePickerElement extends Components.AppRemoteSlidePicker, HTMLStencilElement {
    }
    var HTMLAppRemoteSlidePickerElement: {
        prototype: HTMLAppRemoteSlidePickerElement;
        new (): HTMLAppRemoteSlidePickerElement;
    };
    interface HTMLAppRemoteViewerElement extends Components.AppRemoteViewer, HTMLStencilElement {
    }
    var HTMLAppRemoteViewerElement: {
        prototype: HTMLAppRemoteViewerElement;
        new (): HTMLAppRemoteViewerElement;
    };
    interface HTMLAppRootControlElement extends Components.AppRootControl, HTMLStencilElement {
    }
    var HTMLAppRootControlElement: {
        prototype: HTMLAppRootControlElement;
        new (): HTMLAppRootControlElement;
    };
    interface HTMLAppRootViewElement extends Components.AppRootView, HTMLStencilElement {
    }
    var HTMLAppRootViewElement: {
        prototype: HTMLAppRootViewElement;
        new (): HTMLAppRootViewElement;
    };
    interface HTMLElementTagNameMap {
        "app-bottom-sheet": HTMLAppBottomSheetElement;
        "app-draw": HTMLAppDrawElement;
        "app-logo": HTMLAppLogoElement;
        "app-remote": HTMLAppRemoteElement;
        "app-remote-slide-picker": HTMLAppRemoteSlidePickerElement;
        "app-remote-viewer": HTMLAppRemoteViewerElement;
        "app-root-control": HTMLAppRootControlElement;
        "app-root-view": HTMLAppRootViewElement;
    }
}
declare namespace LocalJSX {
    interface AppBottomSheet {
    }
    interface AppDraw {
        "height"?: number;
        "heightOffset"?: number;
        "slides"?: number;
        "width"?: number;
        "widthOffset"?: number;
    }
    interface AppLogo {
    }
    interface AppRemote {
        "room"?: string;
    }
    interface AppRemoteSlidePicker {
    }
    interface AppRemoteViewer {
    }
    interface AppRootControl {
    }
    interface AppRootView {
    }
    interface IntrinsicElements {
        "app-bottom-sheet": AppBottomSheet;
        "app-draw": AppDraw;
        "app-logo": AppLogo;
        "app-remote": AppRemote;
        "app-remote-slide-picker": AppRemoteSlidePicker;
        "app-remote-viewer": AppRemoteViewer;
        "app-root-control": AppRootControl;
        "app-root-view": AppRootView;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-bottom-sheet": LocalJSX.AppBottomSheet & JSXBase.HTMLAttributes<HTMLAppBottomSheetElement>;
            "app-draw": LocalJSX.AppDraw & JSXBase.HTMLAttributes<HTMLAppDrawElement>;
            "app-logo": LocalJSX.AppLogo & JSXBase.HTMLAttributes<HTMLAppLogoElement>;
            "app-remote": LocalJSX.AppRemote & JSXBase.HTMLAttributes<HTMLAppRemoteElement>;
            "app-remote-slide-picker": LocalJSX.AppRemoteSlidePicker & JSXBase.HTMLAttributes<HTMLAppRemoteSlidePickerElement>;
            "app-remote-viewer": LocalJSX.AppRemoteViewer & JSXBase.HTMLAttributes<HTMLAppRemoteViewerElement>;
            "app-root-control": LocalJSX.AppRootControl & JSXBase.HTMLAttributes<HTMLAppRootControlElement>;
            "app-root-view": LocalJSX.AppRootView & JSXBase.HTMLAttributes<HTMLAppRootViewElement>;
        }
    }
}
